server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_db_v1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true